// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "souls": public TestHelpers
//
// Command:
// $ goagen
// --design=github.com/pmdcosta/dark-souls/design
// --out=$(GOPATH)/src/github.com/pmdcosta/dark-souls
// --version=v1.2.0-dirty

package test
